steps:
  # Build de la imagen Docker
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - "-t"
      - "gcr.io/$PROJECT_ID/user-api"
      - "."

  # Push de la imagen al Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - "gcr.io/$PROJECT_ID/user-api"

  # Deploy a Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - user-api
      - "--image=gcr.io/$PROJECT_ID/user-api"
      - "--region=us-central1"
      - "--platform=managed"
      - "--allow-unauthenticated"

images:
  - "gcr.io/$PROJECT_ID/user-api"
